export const statesList = [
  "Sabhi",
  "Kendra Sarkar",
  "Bihar",
  "Uttar Pradesh",
  "Maharashtra",
  "Rajasthan",
  "Madhya Pradesh",
];

export const updateBlocks = [
  {
    id: "Latest Job",
    title: "Latest Jobs",
    icon: "Briefcase",
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
  },
  {
    id: "Result",
    title: "Results",
    icon: "CheckCircle",
    color: "text-rose-600",
    bg: "bg-rose-50",
    border: "border-rose-200",
  },
  {
    id: "Admit Card",
    title: "Admit Cards",
    icon: "FileText",
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    border: "border-indigo-200",
  },
  {
    id: "Admission",
    title: "Admissions",
    icon: "GraduationCap",
    color: "text-purple-600",
    bg: "bg-purple-50",
    border: "border-purple-200",
  },
];

export const schemesData = [
  {
    id: "s1",
    type: "scheme",
    title: "PM Kisan Samman Nidhi",
    category: "Krishi",
    state: "Kendra Sarkar",
    icon: "Landmark",
    iconColor: "text-emerald-600",
    shortDesc: "Kisano ko har saal ₹6000 ki aarthik sahayata.",
    benefits: "₹2000 ki 3 kisto mein direct bank account transfer.",
    process: [
      "Official website pmkisan.gov.in par jayein.",
      "'New Farmer Registration' option par click karein.",
      "Apna Aadhar number aur captcha code dalein.",
      "Form mein mangi gayi saari jankari bharein aur submit karein.",
    ],
    documents: [
      "Aadhar Card",
      "Zameen ke kagzat",
      "Bank Passbook",
      "Mobile Number",
    ],
  },
  {
    id: "s2",
    type: "scheme",
    title: "Bihar Student Credit Card",
    category: "Shiksha",
    state: "Bihar",
    icon: "GraduationCap",
    iconColor: "text-indigo-500",
    shortDesc: "Uchha shiksha ke liye ₹4 lakh tak ka education loan.",
    benefits: "Bahut kam interest rate par padhai ke liye loan.",
    process: [
      "MNSSBY portal par online registration karein.",
      "Apne zile ke DRCC office mein documents verify karwayein.",
      "Bank se loan approval ka wait karein.",
    ],
    documents: [
      "10th/12th Marksheet",
      "Aadhar Card",
      "Admission Letter",
      "Income Certificate",
    ],
  },
  {
    id: "s3",
    type: "scheme",
    title: "UP Mukhyamantri Kanya Sumangala",
    category: "Shiksha",
    state: "Uttar Pradesh",
    icon: "HeartPulse",
    iconColor: "text-rose-500",
    shortDesc: "Betiyon ke janm se lekar padhai tak aarthik madad.",
    benefits: "Beti ke alag-alag padav par kul ₹15,000 ki sahayata rashi.",
    process: [
      "MKSY UP portal par jayein.",
      "Citizen Login karke naya account banayein.",
      "Beti ki details aur documents upload karein.",
    ],
    documents: [
      "Beti ka Birth Certificate",
      "Parivar ka Income Certificate",
      "Aadhar Card",
      "Bank Details",
    ],
  },
  {
    id: "s4",
    type: "scheme",
    title: "Ayushman Bharat Yojana",
    category: "Swasthya",
    state: "Kendra Sarkar",
    icon: "ShieldCheck",
    iconColor: "text-sky-500",
    shortDesc: "Gareeb parivaron ko ₹5 lakh tak ka muft swasthya bima.",
    benefits: "Sarkari aur private hospitals mein muft ilaj ki suvidha.",
    process: [
      "Mera.pmjay.gov.in par jakar apni eligibility check karein.",
      "Apne nazdeeki CSC ya hospital jayein.",
      "Ayushman Golden Card banwayein.",
    ],
    documents: ["Aadhar Card", "Ration Card", "Mobile Number"],
  },
  {
    id: "s5",
    type: "scheme",
    title: "Majhi Ladki Bahin Yojana",
    category: "Aarthik Madad",
    state: "Maharashtra",
    icon: "Users",
    iconColor: "text-purple-500",
    shortDesc: "Mahilao ko har mahine ₹1500 ki aarthik sahayata.",
    benefits:
      "Patra mahilao ke bank account mein seedhe ₹1500 pratimah transfer.",
    process: [
      "Nari Shakti Doot App download karein ya online portal par jayein.",
      "Apna mobile number register karein.",
      "Form bharein aur required documents upload karein.",
    ],
    documents: [
      "Aadhar Card",
      "Domicile Certificate",
      "Bank Account (Aadhar linked)",
      "Income Proof",
    ],
  },
];

export const updatesData = [
  {
    id: "u1",
    type: "update",
    category: "Latest Job",
    title: "SSC CGL 2026 Apply Online",
    department: "SSC",
    state: "Kendra Sarkar",
    vacancies: "8,500+",
    qualification: "Graduation",
    lastDate: "25 March 2026",
    shortDesc: "Kendra sarkar ke vibhinn mantralayo mein bharti.",
    benefits: "Level 4 se Level 8 tak ki salary.",
    process: ["ssc.gov.in par OTR karein.", "Form bharein aur fee pay karein."],
    documents: ["Photo", "Signature", "Marksheets"],
  },
  {
    id: "u2",
    type: "update",
    category: "Latest Job",
    title: "Bihar Police Constable 2026",
    department: "CSBC",
    state: "Bihar",
    vacancies: "21,391",
    qualification: "12th Pass",
    lastDate: "15 April 2026",
    shortDesc: "Bihar Police mein sipahi pado par bharti.",
    benefits: "Level 3 Salary + allowances.",
    process: ["csbc.bih.nic.in par jayein.", "Online application bharein."],
    documents: ["12th Certificate", "Aadhar Card", "Domicile"],
  },
  {
    id: "u3",
    type: "update",
    category: "Result",
    title: "UPPSC PCS 2025 Pre Result",
    department: "UPPSC",
    state: "Uttar Pradesh",
    vacancies: "250+",
    qualification: "Graduation",
    lastDate: "Declared",
    shortDesc: "UPPSC PCS Prelims exam ka result ghoshit.",
    benefits: "Mains exam ke liye qualify hone wale candidates ki list.",
    process: [
      "uppsc.up.nic.in par jayein.",
      "Result PDF download karein aur Roll No. search karein.",
    ],
    documents: ["Admit Card (Roll No. ke liye)"],
  },
  {
    id: "u4",
    type: "update",
    category: "Result",
    title: "CTET Jan 2026 Result",
    department: "CBSE",
    state: "Kendra Sarkar",
    vacancies: "N/A",
    qualification: "B.Ed / D.El.Ed",
    lastDate: "Declared",
    shortDesc: "Central Teacher Eligibility Test ka result.",
    benefits: "Teachers recruitment ke liye eligibility certificate.",
    process: [
      "ctet.nic.in par jayein.",
      "Roll number daalkar score card download karein.",
    ],
    documents: ["CTET Admit Card"],
  },
  {
    id: "u5",
    type: "update",
    category: "Admit Card",
    title: "Railway ALP CBT 1 Admit Card",
    department: "RRB",
    state: "Kendra Sarkar",
    vacancies: "5,696",
    qualification: "ITI / Diploma",
    lastDate: "Exam: 10 May",
    shortDesc: "Assistant Loco Pilot CBT 1 exam ke admit card.",
    benefits: "Exam centre aur shift ki jankari.",
    process: [
      "Apne zone ki RRB website par login karein.",
      "E-call letter download aur print karein.",
    ],
    documents: ["Registration Number", "DOB Password"],
  },
  {
    id: "u6",
    type: "update",
    category: "Admission",
    title: "NTA CUET UG 2026 Apply",
    department: "NTA",
    state: "Kendra Sarkar",
    vacancies: "N/A",
    qualification: "12th Pass",
    lastDate: "30 April 2026",
    shortDesc: "Central Universities me UG courses me admission.",
    benefits: "Top universities me admission ka mauka.",
    process: [
      "cuet.samarth.ac.in par registration karein.",
      "Subjects select karein aur fee pay karein.",
    ],
    documents: ["12th Marksheet", "Photo", "Sign", "Aadhar"],
  },
];
