'use client'
import { useState, useEffect } from 'react'

export default function AiSection({ content, title, type }) {
  const [summary, setSummary] = useState('')
  const [faqs, setFaqs] = useState([])
  const [loadingSummary, setLoadingSummary] = useState(false)
  const [loadingFaqs, setLoadingFaqs] = useState(false)
  const [faqOpen, setFaqOpen] = useState(null)

  useEffect(() => {
    if (!content) return
    // Fetch Summary
    setLoadingSummary(true)
    fetch('/api/ai/summarize', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content, title, type }),
    })
      .then(r => r.json())
      .then(d => { setSummary(d.summary || ''); setLoadingSummary(false) })
      .catch(() => setLoadingSummary(false))

    // Fetch FAQs
    setLoadingFaqs(true)
    fetch('/api/ai/faq', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content, title }),
    })
      .then(r => r.json())
      .then(d => { setFaqs(d.faqs || []); setLoadingFaqs(false) })
      .catch(() => setLoadingFaqs(false))
  }, [content, title, type])

  return (
    <div className="mb-6 space-y-4">
      {/* AI Summary Box */}
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-5">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-lg">🤖</span>
          <span className="text-xs font-bold text-amber-700 uppercase tracking-wider">AI Assistant — Quick Summary</span>
        </div>
        {loadingSummary ? (
          <div className="space-y-2 animate-pulse">
            <div className="h-3 bg-amber-200 rounded w-full"></div>
            <div className="h-3 bg-amber-200 rounded w-5/6"></div>
            <div className="h-3 bg-amber-200 rounded w-4/6"></div>
          </div>
        ) : summary ? (
          <p className="text-sm text-gray-700 leading-relaxed">{summary}</p>
        ) : (
          <p className="text-sm text-amber-600 italic">Generating AI summary...</p>
        )}
        <p className="text-[10px] text-gray-400 mt-3">Generated by AI. Please verify from official source before applying.</p>
      </div>

      {/* AI FAQ Section */}
      {(loadingFaqs || faqs.length > 0) && (
        <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5">
          <h3 className="font-bold text-[#1e3a5f] text-base mb-4 flex items-center gap-2">
            <span>❓</span> Frequently Asked Questions
          </h3>
          {loadingFaqs ? (
            <div className="space-y-3 animate-pulse">
              {[1,2,3].map(i => (
                <div key={i} className="border border-gray-100 rounded-lg p-3">
                  <div className="h-3 bg-gray-200 rounded w-3/4 mb-2"></div>
                  <div className="h-3 bg-gray-100 rounded w-full"></div>
                </div>
              ))}
            </div>
          ) : (
            <div className="space-y-2">
              {faqs.map((faq, i) => (
                <div key={i} className="border border-gray-100 rounded-lg overflow-hidden">
                  <button
                    className="w-full text-left px-4 py-3 flex justify-between items-start gap-3 hover:bg-gray-50 transition-colors"
                    onClick={() => setFaqOpen(faqOpen === i ? null : i)}
                  >
                    <span className="text-sm font-medium text-gray-800">{faq.question}</span>
                    <span className="text-gray-400 shrink-0 text-lg mt-0.5">{faqOpen === i ? '\u2212' : '+'}</span>
                  </button>
                  {faqOpen === i && (
                    <div className="px-4 py-3 bg-gray-50 border-t border-gray-100">
                      <p className="text-sm text-gray-600 leading-relaxed">{faq.answer}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
